# Generated by Django 4.2.15 on 2024-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_APP', '0002_alter_task_priority_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not completed', 'Working'), ('completed', 'Completed'), ('dead', 'Dead')], default='not completed', max_length=20),
        ),
    ]
