# Generated by Django 4.2.15 on 2024-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI_APP', '0004_notification_task_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('dead', 'Dead'), ('not completed', 'Working'), ('completed', 'Completed')], default='not completed', max_length=20),
        ),
    ]
